version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 28
    directory: /
    schedule:
      interval: "yearly"
    assignees:
      - "stkom"
    reviewers:
      - "stkom"
